/**
 * Supabase generated database types.
 *
 * SOURCE OF TRUTH: the SQL under `supabase/migrations`. In a provisioned
 * environment this file is regenerated by `pnpm supabase:types`
 * (`supabase gen types typescript`). It is hand-authored here to mirror the
 * committed migrations so the workspace typechecks without a live database.
 *
 * Do not import TypeScript application schemas here — this is the DB contract,
 * distinct from the Zod application schemas in @repo/shared-schemas.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type Timestamps = {
  created_at: string;
  updated_at: string;
};

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          full_name: string | null;
        } & Timestamps;
        Insert: {
          id: string;
          role?: Database["public"]["Enums"]["app_role"];
          full_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          full_name?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      accounts: {
        Row: {
          id: string;
          name: string;
          domain: string | null;
          owner_id: string;
          tier: Database["public"]["Enums"]["account_tier"];
          lifecycle_stage: Database["public"]["Enums"]["lifecycle_stage"];
          industry: string | null;
          employee_count: number | null;
          annual_revenue_usd: number | null;
          open_pipeline_usd: number;
          last_contacted_at: string | null;
          health_score: number | null;
          intent_signals: string[];
          data_quality_flags: string[];
        } & Timestamps;
        Insert: {
          id?: string;
          name: string;
          domain?: string | null;
          owner_id: string;
          tier: Database["public"]["Enums"]["account_tier"];
          lifecycle_stage: Database["public"]["Enums"]["lifecycle_stage"];
          industry?: string | null;
          employee_count?: number | null;
          annual_revenue_usd?: number | null;
          open_pipeline_usd?: number;
          last_contacted_at?: string | null;
          health_score?: number | null;
          intent_signals?: string[];
          data_quality_flags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["accounts"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "accounts_owner_id_fkey";
            columns: ["owner_id"];
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      contacts: {
        Row: {
          id: string;
          account_id: string;
          first_name: string;
          last_name: string;
          title: string | null;
          email: string | null;
          role: Database["public"]["Enums"]["contact_role"];
          is_primary: boolean;
          last_engaged_at: string | null;
        } & Timestamps;
        Insert: {
          id?: string;
          account_id: string;
          first_name: string;
          last_name: string;
          title?: string | null;
          email?: string | null;
          role?: Database["public"]["Enums"]["contact_role"];
          is_primary?: boolean;
          last_engaged_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["contacts"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "contacts_account_id_fkey";
            columns: ["account_id"];
            referencedRelation: "accounts";
            referencedColumns: ["id"];
          },
        ];
      };
      opportunities: {
        Row: {
          id: string;
          account_id: string;
          name: string;
          stage: Database["public"]["Enums"]["opportunity_stage"];
          amount_usd: number;
          probability: number;
          close_date: string | null;
          is_closed: boolean;
          is_won: boolean;
          next_step: string | null;
        } & Timestamps;
        Insert: {
          id?: string;
          account_id: string;
          name: string;
          stage: Database["public"]["Enums"]["opportunity_stage"];
          amount_usd?: number;
          probability?: number;
          close_date?: string | null;
          is_closed?: boolean;
          is_won?: boolean;
          next_step?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["opportunities"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "opportunities_account_id_fkey";
            columns: ["account_id"];
            referencedRelation: "accounts";
            referencedColumns: ["id"];
          },
        ];
      };
      activities: {
        Row: {
          id: string;
          account_id: string;
          contact_id: string | null;
          type: Database["public"]["Enums"]["activity_type"];
          subject: string | null;
          body: string | null;
          occurred_at: string;
          created_by_id: string;
          verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          contact_id?: string | null;
          type: Database["public"]["Enums"]["activity_type"];
          subject?: string | null;
          body?: string | null;
          occurred_at: string;
          created_by_id: string;
          verified?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activities"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "activities_account_id_fkey";
            columns: ["account_id"];
            referencedRelation: "accounts";
            referencedColumns: ["id"];
          },
        ];
      };
      recommendations: {
        Row: {
          id: string;
          run_id: string;
          account_id: string;
          owner_id: string;
          score: number;
          rank: number;
          confidence: number;
          reason_codes: string[];
          reason_narrative: string;
          next_best_action: Json;
          source_signals: Json;
          verification: Json;
          approval_status: Database["public"]["Enums"]["approval_status"];
          published: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          account_id: string;
          owner_id: string;
          score: number;
          rank: number;
          confidence: number;
          reason_codes: string[];
          reason_narrative: string;
          next_best_action: Json;
          source_signals: Json;
          verification: Json;
          approval_status?: Database["public"]["Enums"]["approval_status"];
          published?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["recommendations"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "recommendations_account_id_fkey";
            columns: ["account_id"];
            referencedRelation: "accounts";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_evidence: {
        Row: {
          id: string;
          run_id: string | null;
          account_id: string | null;
          actor_id: string;
          action: string;
          decision: Database["public"]["Enums"]["audit_decision"];
          reason: string;
          evidence: Json;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          run_id?: string | null;
          account_id?: string | null;
          actor_id: string;
          action: string;
          decision: Database["public"]["Enums"]["audit_decision"];
          reason: string;
          evidence?: Json;
          occurred_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["audit_evidence"]["Insert"]>;
        Relationships: [];
      };
      eval_results: {
        Row: {
          id: string;
          suite: string;
          kind: string;
          passed: boolean;
          pass_rate: number;
          threshold: number;
          deployment_blocking: boolean;
          details: Json;
          ran_at: string;
        };
        Insert: {
          id?: string;
          suite: string;
          kind: string;
          passed: boolean;
          pass_rate: number;
          threshold: number;
          deployment_blocking?: boolean;
          details?: Json;
          ran_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["eval_results"]["Insert"]>;
        Relationships: [];
      };
      observability_events: {
        Row: {
          id: string;
          source: string;
          name: string;
          level: string;
          trace_id: string | null;
          attributes: Json;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          source: string;
          name: string;
          level?: string;
          trace_id?: string | null;
          attributes?: Json;
          occurred_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["observability_events"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      current_app_role: {
        Args: Record<string, never>;
        Returns: Database["public"]["Enums"]["app_role"];
      };
    };
    Enums: {
      app_role: "rep" | "manager" | "admin";
      account_tier: "strategic" | "enterprise" | "mid_market" | "smb";
      lifecycle_stage:
        | "prospect"
        | "open_opportunity"
        | "customer"
        | "renewal"
        | "churn_risk"
        | "dormant";
      contact_role:
        | "economic_buyer"
        | "champion"
        | "technical_evaluator"
        | "influencer"
        | "blocker"
        | "unknown";
      opportunity_stage:
        | "discovery"
        | "qualification"
        | "proposal"
        | "negotiation"
        | "closed_won"
        | "closed_lost";
      activity_type:
        | "call"
        | "email_outbound"
        | "email_inbound"
        | "meeting"
        | "note"
        | "task"
        | "intent_event";
      approval_status: "not_required" | "pending_approval" | "approved" | "rejected";
      audit_decision: "allowed" | "blocked" | "approved" | "rejected";
    };
    CompositeTypes: Record<string, never>;
  };
}

/** Convenience helpers for table Row/Insert/Update types. */
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
