#!/usr/bin/env bash
# Acceptance A — deterministic baseline.
#
# The gate owns the model-disabled profile. The migration verifier keeps one
# migrated throwaway PostgreSQL instance alive and then runs the Acceptance A
# Turbo task against that same database. The exact recommendation generated by
# the real deterministic runtime is persisted through the production Supabase
# repository method and continues through RLS read, exact-payload approval,
# protected execution, and durable follow-up.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

fail() {
  echo "FAILED: Acceptance A — $*" >&2
  exit 1
}

export RUNTIME_DRAFTING_ENABLED=false
export VERIFY_ACCEPTANCE_A_RUNTIME=true
unset RUNTIME_DRAFT_API_KEY RUNTIME_DRAFT_MODEL

[ "$RUNTIME_DRAFTING_ENABLED" = "false" ] || fail "runtime drafting must be disabled"

echo "==> Acceptance A: one model-disabled durable production spine"
pnpm verify:migrations \
  || fail "model-disabled durable production spine"

echo "PASSED: Acceptance A — deterministic baseline end to end."
